---
variables:
  LATEX_IMAGE: andonome/texbind

build:
  image: $LATEX_IMAGE
  script:
    - make -j 2 -O all
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "run"
  artifacts:
    paths:
      - "*.pdf"
